import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../providers/theme-provider";
import { Toaster } from 'sonner'
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });
console.log("Publishable Key:", process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body  suppressHydrationWarning  className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
             {children}
             <Toaster/>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
   
  );
}


